### ISSUE TITLE
auto-position the popup further to right of the sidebar?

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/otl-covenants#14]
@ilyankou -- Your restrictive covenant revision map is wonderful, but I need to ask for one tiny modification to make it more accessible for some of our readers. They perceive that the popup text appears "cropped off" when viewing the [smaller-sized map inside this book chapter](https://ontheline.trincoll.edu/restricting.html) -- see screenshot below.

Can you auto-position the pop-up window, not in the center of the map, but slightly to the right so that it's less likely to be hidden by the new sidebar?

Yes, I know that readers can simply slide the map to the right, or click on the full-screen version, but some of our valued senior citizens have expressed concerns, so perhaps you can make this small adjustment

<img width="743" alt="Screenshot 2024-01-23 at 1 14 57 PM" src="https://github.com/OnTheLine/otl-covenants/assets/649719/d36011b7-5f02-45b3-8186-424fb406394e">

**Comment by ilyankou** [comment]
Hi @JackDougherty 

I think ideally you'd want the popup to be displayed on top of the control, which is not quite straightforward. z-index, which normally determines the order of CSS layers, is powerless here (see https://github.com/Leaflet/Leaflet/issues/4811).

Let me revisit this later when I have some free time.
